
import Head from "next/head";
import Footer from "./HomeLayout/Footer";
import CardsFooter from "./HomeLayout/CardsFooter";
const Layout = ({ children }) => (

  <>
    <Head>
      <title className="meta">PharmaTrace NFT Marketplace</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    {children}
    <CardsFooter />
    <Footer />
  </>
);

export default Layout;
